const SAVE_KEY='yefeng_v08_save', OLD_KEYS=['yefeng_v07_save','yefeng_v061_save','yefeng_v06_save'];
const ROLES=['上路','打野','中路','下路','輔助'], DAYS=['一','二','三','四','五','六','日'];
const WD=['放學後','晚間','深夜'], WE=['上午','下午','傍晚','晚間','深夜'];
function fresh(){return {version:'0.8',started:false,player:{name:'夜鋒',age:16,role:'中路',cash:8000,rank:'鑽石 IV',lp:23,wins:0,losses:0,followers:0,proAttention:0,energy:82,stress:22,mood:72,passion:91,school:62,family:28,relations:{阿哲:64},stats:{操作:61,反應:65,對線:58,補刀:62,換血:57,團戰:56,遊戲理解:52,地圖意識:51,決策:48,心態:57,英雄池:45,溝通:50}},date:{year:2026,month:9,week:1,day:1},dayState:{usedSlots:0,actions:[]},weeklyPlan:{},characters:{阿哲:{known:true,desc:'高中好友，喜歡MOBA。'},林雨晴:{known:false,desc:'同班同學。'},Kaito:{known:false,desc:'高分段玩家。'}},flags:{},logs:['新的學期開始了。你還只是個默默無名的16歲高中生。'],news:['本週高分段競爭激烈，多名年輕玩家開始衝擊宗師。'],messages:[{id:'a1',from:'阿哲',text:'今天晚上要不要雙排？我剛上翡翠。',unread:true,replied:false,type:'duo'}]}}
function norm(s){s.dayState??={usedSlots:0,actions:[]};s.weeklyPlan??={};s.player.relations??={阿哲:64};s.characters??=fresh().characters;s.flags??={};s.messages??=[];s.version='0.8';return s}
function load(){for(const k of [SAVE_KEY,...OLD_KEYS]){try{let s=JSON.parse(localStorage.getItem(k));if(s)return norm(s)}catch(e){}}return fresh()}
let state=load(),tab='home'; const save=()=>localStorage.setItem(SAVE_KEY,JSON.stringify(state));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
const avg=()=>Object.values(state.player.stats).reduce((a,b)=>a+b,0)/Object.keys(state.player.stats).length;
const slots=()=>state.date.day<=5?WD:WE, remain=()=>slots().length-state.dayState.usedSlots;
function consume(name,n=1){if(remain()<n)return false;for(let i=0;i<n;i++){state.dayState.actions.push(slots()[state.dayState.usedSlots]+'：'+name);state.dayState.usedSlots++}return true}
const S=(l,v)=>`<div class="stat"><div class="label">${l}</div><div class="value">${v}</div></div>`;
const B=(l,v,rev=false)=>`<div style="margin:10px 0"><div class="row space"><span>${l}</span><span class="small">${Math.round(rev?100-v:v)}/100</span></div><div class="bar"><span style="width:${clamp(v,0,100)}%"></span></div></div>`;
function start(){return `<section class="card hero"><div class="eyebrow">2026 · 一切從零開始</div><h2 style="font-size:28px">登頂之路：夜鋒</h2><p class="small">16歲，高二。從零開始追逐職業夢。</p></section><section class="card"><input id="nameInput" value="夜鋒" style="width:100%;padding:12px;border-radius:12px;border:1px solid var(--line);background:#0b1324;color:white"><h3>選擇主位置</h3><div class="choice-grid">${ROLES.map(r=>`<button class="choice ${r==='中路'?'selected':''}" data-role="${r}"><strong>${r}</strong></button>`).join('')}</div><button id="startBtn" class="btn" style="width:100%;margin-top:12px">開始新生涯</button></section>`}
function appointment(){let a=(state.weeklyPlan[state.date.day]||[]).filter(x=>!x.completed);if(!a.length)return '';return `<section class="card"><div class="row space"><h2>今日約定</h2><span class="badge">不可忘記</span></div>${a.map(x=>`<div class="schedule-item"><div><strong>${x.slot} · ${x.title}</strong><div class="small">答應的活動已正式排入今天。</div></div><button class="ghost run-appt" data-id="${x.id}">前往</button></div>`).join('')}</section>`}
function action(t,title,cost){return `<button class="choice action-btn" data-action="${t}" ${remain()<cost?'disabled':''}><strong>${title}</strong><span class="small">${cost}時段</span></button>`}
function home(){let p=state.player;return `<section class="card hero"><div class="row space"><div><div class="small">2026年9月 · 第${state.date.week}週 · 週${DAYS[state.date.day-1]}</div><h2>${p.name} · ${p.age}歲 · ${p.role}</h2></div><span class="badge">綜合 ${avg().toFixed(1)}</span></div><div class="stat-grid">${S('Rank',p.rank+' '+p.lp+' LP')}${S('現金','NT$'+p.cash.toLocaleString())}${S('職業關注',p.proAttention+'/100')}${S('粉絲',p.followers)}</div></section><section class="card"><div class="row space"><h2>今日時間</h2><span class="badge">剩餘 ${remain()} 格</span></div><div class="slot-grid">${slots().map((x,i)=>`<div class="slot ${i<state.dayState.usedSlots?'used':''} ${i===state.dayState.usedSlots?'current':''}"><strong>${x}</strong><div class="small">${state.dayState.actions[i]?.split('：')[1]||'未安排'}</div></div>`).join('')}</div></section>${appointment()}<section class="card"><h2>今日狀態</h2>${B('體力',p.energy)}${B('心情',p.mood)}${B('壓力',100-p.stress,true)}${B('遊戲熱情',p.passion)}</section><section class="card"><h2>今天要做什麼？</h2><div class="choice-grid">${action('rank','🎮 Rank',1)}${action('train','🏋️ 訓練',1)}${action('study','📚 讀書',1)}${action('stream','📺 直播',1)}${action('social','👥 社交',1)}${action('work','💼 打工',2)}${action('shop','🛒 外出/購物',1)}${action('rest','🛏️ 休息',1)}</div><button id="nextDayBtn" class="btn secondary" style="width:100%;margin-top:12px">${remain()?'提早結束今天':'進入下一天'}</button></section><section class="card"><h2>最近紀錄</h2>${state.logs.slice(-6).reverse().map(x=>`<div class="log">${x}</div>`).join('')}</section>`}
function schedule(){return `<section class="card"><div class="row space"><h2>本週行程</h2><span class="badge">第${state.date.week}週</span></div><div class="timeline">${DAYS.map((d,i)=>`<div class="day-chip"><strong>週${d}</strong><div class="small">${(state.weeklyPlan[i+1]||[]).map(x=>x.slot+' '+x.title+(x.completed?' ✓':'')).join(' · ')||'尚無特殊行程'}</div></div>`).join('')}</div></section><section class="card"><div class="notice">現在答應邀約後會直接寫入對應時段；提早結束一天時，也會先處理尚未完成的約定。</div></section>`}
function rank(){let p=state.player,wr=p.wins+p.losses?Math.round(p.wins/(p.wins+p.losses)*100):0;return `<section class="card rank-card" style="text-align:center"><div class="eyebrow">RANKED SOLO</div><div class="big-number">${p.rank}</div><div>${p.lp} LP</div><p class="small">${p.wins}勝 ${p.losses}敗 · 勝率${wr}%</p><button class="btn action-btn" data-action="rank" ${remain()<1?'disabled':''}>開始配對</button></section><section class="card"><h2>能力摘要</h2><div class="stat-grid">${Object.entries(p.stats).map(([k,v])=>S(k,v.toFixed(1))).join('')}</div></section>`}
function phone(){let unread=state.messages.filter(m=>m.unread).length;return `<section class="card"><div class="row space"><h2>訊息</h2><span class="badge">${unread} 未讀</span></div>${state.messages.slice().reverse().map(m=>`<div class="message ${m.unread?'unread':''}"><button class="message-open" data-msg="${m.id}" style="width:100%;border:0;background:transparent;color:white;text-align:left;padding:0"><div class="meta"><strong>${m.from}</strong><span class="small">${m.replied?'已回覆':m.unread?'未讀':'已讀'}</span></div><div style="margin-top:6px;white-space:pre-line">${m.text}</div><div class="small" style="margin-top:8px">點擊開啟對話 ›</div></button></div>`).join('')}</section><section class="card"><h2>人物</h2>${Object.entries(state.characters).filter(([k,c])=>c.known).map(([k,c])=>`<div class="log"><strong>${k}</strong><div class="small">${c.desc}</div></div>`).join('')}</section><section class="card"><h2>電競新聞</h2>${state.news.slice().reverse().map(n=>`<div class="log">${n}</div>`).join('')}</section>`}
function career(){let p=state.player;return `<section class="card"><h2>生涯檔案</h2><div class="stat-grid">${S('學業',Math.round(p.school))}${S('家庭支持',Math.round(p.family))}${S('阿哲關係',Math.round(p.relations.阿哲))}${S('粉絲',p.followers)}</div></section><section class="card"><h2>版本</h2><div class="log"><strong>V0.8</strong>｜訊息修正、約定可執行、生活奇遇與新人物。</div></section>`}
function render(){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));let m=document.querySelector('#main');if(!state.started){m.innerHTML=start();bindStart();return}m.innerHTML=tab==='home'?home():tab==='schedule'?schedule():tab==='rank'?rank():tab==='phone'?phone():career();bind()}
function bindStart(){document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-role]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.player.role=b.dataset.role});document.querySelector('#startBtn').onclick=()=>{state.player.name=document.querySelector('#nameInput').value.trim()||'夜鋒';state.started=true;save();render()}}
function bind(){document.querySelectorAll('.action-btn').forEach(b=>b.onclick=()=>act(b.dataset.action));document.querySelector('#nextDayBtn')?.addEventListener('click',nextDay);document.querySelectorAll('.message-open').forEach(b=>b.onclick=e=>{e.preventDefault();openMessage(b.dataset.msg)});document.querySelectorAll('.run-appt').forEach(b=>b.onclick=()=>goAppointment(b.dataset.id))}
function simple(name,cost,fn){if(!consume(name,cost))return;let d=fn();state.logs.push(name+'完成：'+d);save();render();modal(`<h2>${name}完成</h2><p>${d}</p>${closeBtn()}`)}
function act(t){if(t==='rank')playRank(false);if(t==='train')simple('訓練',1,()=>{let k=Object.keys(state.player.stats)[rand(0,11)];state.player.stats[k]+=Math.random()*.2+.08;state.player.energy-=8;return k+'獲得微幅成長。'});if(t==='study')simple('讀書',1,()=>{state.player.school=clamp(state.player.school+1.2,0,100);state.player.family=clamp(state.player.family+.5,0,100);state.player.energy-=5;return '學業與家庭支持略微提升。'});if(t==='rest')simple('休息',1,()=>{state.player.energy=clamp(state.player.energy+18,0,100);state.player.stress=clamp(state.player.stress-8,0,100);state.player.mood=clamp(state.player.mood+4,0,100);return '體力恢復，壓力下降。'});if(t==='work')simple('打工',2,()=>{state.player.cash+=1200;state.player.energy-=17;return '收入 NT$1,200。'});if(t==='stream')chooseStream();if(t==='social')chooseSocial();if(t==='shop')simple('外出/購物',1,()=>{let c=Math.min(120,state.player.cash);state.player.cash-=c;state.player.mood+=2;return '買了飲料與點心，花費 NT$'+c+'。'})}
function playRank(duo){if(!consume(duo?'與阿哲雙排':'Rank',1))return;let p=state.player,win=avg()+(p.mood-50)*.05-p.stress*.05+rand(-8,8)>=54,delta=win?rand(19,27):-rand(17,24);win?p.wins++:p.losses++;p.lp+=delta;p.energy=clamp(p.energy-6,0,100);p.mood=clamp(p.mood+(win?3:-4),0,100);if(duo)p.relations.阿哲=clamp(p.relations.阿哲+2,0,100);adjustRank();state.logs.push(`${duo?'與阿哲雙排':'Rank'}：${win?'勝利':'敗北'}，${delta>0?'+':''}${delta} LP。`);save();render();modal(`<h2 class="${win?'goodtext':'badtext'}">${win?'勝利':'敗北'}</h2><p>${duo?'你和阿哲完成了今晚的約定。':''}</p><div class="big-number">${delta>0?'+':''}${delta} LP</div>${closeBtn()}`)}
function adjustRank(){let p=state.player,o=['鑽石 IV','鑽石 III','鑽石 II','鑽石 I'];let i=o.indexOf(p.rank);if(i>=0&&p.lp>=100){p.lp-=100;p.rank=i<3?o[i+1]:'大師'}if(p.lp<0)p.lp=0}
function chooseStream(){if(remain()<1)return;modal(`<h2>直播內容</h2><div class="reply-grid">${['Rank實況','教學台','雜談','娛樂場'].map(x=>`<button class="reply stream-pick" data-v="${x}">${x}</button>`).join('')}</div>`);setTimeout(()=>document.querySelectorAll('.stream-pick').forEach(b=>b.onclick=()=>{consume('直播',1);let g=rand(2,9);state.player.followers+=g;state.player.energy-=7;state.logs.push(`直播「${b.dataset.v}」，新增 ${g} 位粉絲。`);save();document.querySelector('.modal-backdrop')?.remove();render()}),0)}
function chooseSocial(){if(remain()<1)return;modal(`<h2>社交</h2><div class="reply-grid"><button class="reply social-pick">找阿哲聊天</button></div>`);setTimeout(()=>document.querySelector('.social-pick').onclick=()=>{consume('社交',1);state.player.relations.阿哲+=2;state.player.mood+=5;state.logs.push('你和阿哲聊了一陣子。');save();document.querySelector('.modal-backdrop')?.remove();render()},0)}
function addPlan(title,slot,type){state.weeklyPlan[state.date.day]??=[];let e={id:type+'-'+Date.now(),title,slot,type,completed:false};state.weeklyPlan[state.date.day].push(e);return e}
function openMessage(id){let m=state.messages.find(x=>x.id===id);if(!m)return;m.unread=false;save();if(m.type==='duo'&&!m.replied){modal(`<h2>阿哲</h2><p>${m.text}</p><div class="reply-grid"><button class="reply rduo" data-r="yes">好啊，晚上一起打。</button><button class="reply rduo" data-r="no">今天先不要，下次吧。</button><button class="reply rduo" data-r="seen">先已讀。</button></div>`);setTimeout(()=>document.querySelectorAll('.rduo').forEach(b=>b.onclick=()=>replyDuo(m,b.dataset.r)),0)}else if(m.type==='rain'&&!m.replied){modal(`<h2>林雨晴</h2><p>${m.text}</p><div class="reply-grid"><button class="reply rgirl" data-r="rank">最近都在練Rank。</button><button class="reply rgirl" data-r="joke">因為我在等雨啊。</button><button class="reply rgirl" data-r="short">嗯，差不多。</button></div>`);setTimeout(()=>document.querySelectorAll('.rgirl').forEach(b=>b.onclick=()=>replyGirl(m,b.dataset.r)),0)}else modal(`<h2>${m.from}</h2><p style="white-space:pre-line">${m.text}</p>${closeBtn()}`);render()}
function replyDuo(m,r){m.replied=true;if(r==='yes'){addPlan('與阿哲雙排','晚間','duo');m.text+='\n\n你：好啊，晚上一起打。';state.player.relations.阿哲+=1;state.messages.push({id:'a2-'+Date.now(),from:'阿哲',text:'行，那九點上線！我等你。',unread:true,replied:true,type:'normal'});state.logs.push('你答應阿哲今晚雙排；晚間活動已被鎖定。')}else if(r==='no'){m.text+='\n\n你：今天先不要，下次吧。';state.messages.push({id:'a3-'+Date.now(),from:'阿哲',text:'OK，下次再約。',unread:true,replied:true,type:'normal'})}else m.text+='\n\n（已讀）';save();document.querySelector('.modal-backdrop')?.remove();render()}
function replyGirl(m,r){m.replied=true;state.characters.林雨晴.known=true;let ans=r==='rank'?'最近都在練Rank。':r==='joke'?'因為我在等雨啊。':'嗯，差不多。';m.text+='\n\n你：'+ans;state.messages.push({id:'g2-'+Date.now(),from:'林雨晴',text:r==='rank'?'Rank？你很厲害嗎？下次讓我看看。':r==='joke'?'……這句有點冷欸 😂':'原來如此，那明天見。',unread:true,replied:true,type:'normal'});save();document.querySelector('.modal-backdrop')?.remove();render()}
function goAppointment(id){let e=(state.weeklyPlan[state.date.day]||[]).find(x=>x.id===id&&!x.completed);if(!e)return;let idx=slots().indexOf(e.slot);if(state.dayState.usedSlots<idx){modal(`<h2>還沒到約定時間</h2><p>活動安排在「${e.slot}」。先完成前面的時段，或按「提早結束今天」推進到約定時間。</p>${closeBtn()}`);return}runAppointment(e)}
function runAppointment(e){if(e.type==='duo'){e.completed=true;playRank(true);return true}return false}
function lifeEvent(){if(state.date.week===1&&state.date.day===2&&!state.flags.rain){state.flags.rain=true;state.characters.林雨晴.known=true;state.messages.push({id:'rain-'+Date.now(),from:'林雨晴',text:'剛剛謝謝你借我傘。你每天放學都這麼晚走嗎？',unread:true,replied:false,type:'rain'});state.logs.push('奇遇：放學突然下雨，你在校門口遇見同班的林雨晴。');return '放學突然下起大雨。你把傘借給了沒帶傘的同班同學林雨晴，兩人第一次真正聊上幾句。'}if(state.date.week===1&&state.date.day===4&&!state.flags.kaito){state.flags.kaito=true;state.characters.Kaito.known=true;state.logs.push('Rank奇遇：你連續兩局排到高分段玩家 Kaito，他主動加了你的好友。');return '你連續兩局遇到同一名高分段玩家 Kaito。第二局後，他主動加了你的好友。'}if(Math.random()<.22){let a=['回家路上看到新開的電競館正在徵高中生盃隊伍。','班導突然宣布下週有小考，最近課業不能完全放掉。','你在便利商店碰到以前國中的朋友，聊了十幾分鐘。','Rank排隊時收到陌生人的好友邀請，對方說看過你的對局。','社群上有人剪了你的精彩操作片段，但目前只有少量觀看。'];let e=a[rand(0,a.length-1)];state.logs.push('生活事件：'+e);return e}return null}
function nextDay(){let pending=(state.weeklyPlan[state.date.day]||[]).find(x=>!x.completed);if(pending){let idx=slots().indexOf(pending.slot);while(state.dayState.usedSlots<idx)consume('自由時間',1);if(runAppointment(pending))return}state.date.day++;state.player.energy=clamp(state.player.energy+10,0,100);state.player.stress=clamp(state.player.stress-2,0,100);state.dayState={usedSlots:0,actions:[]};if(state.date.day>7){state.date.day=1;state.date.week++;state.player.cash+=750;state.logs.push(`第${state.date.week-1}週結束：零用錢入帳 NT$750。`)}let e=lifeEvent();save();render();if(e)modal(`<h2>生活奇遇</h2><p>${e}</p>${closeBtn()}`)}
function closeBtn(){return `<button class="btn close-modal" style="width:100%;margin-top:10px">繼續</button>`}function modal(h){document.querySelector('.modal-backdrop')?.remove();let t=document.querySelector('#modalTemplate'),n=t.content.cloneNode(true);n.querySelector('.modal-content').innerHTML=h;document.body.appendChild(n);document.querySelectorAll('.close-modal').forEach(b=>b.onclick=()=>{document.querySelector('.modal-backdrop')?.remove();render()})}
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});document.querySelector('#resetBtn').onclick=()=>{if(confirm('確定刪除目前存檔並重開嗎？')){[SAVE_KEY,...OLD_KEYS].forEach(k=>localStorage.removeItem(k));state=fresh();tab='home';render()}};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));render();
